blank_issues_enabled: false
contact_links:
  - name: "📖 Contribution Guidelines"
    url: https://github.com/aditsuru-git/prism-terminal/blob/main/.github/contributing.md
    about: "Please read our contribution guidelines before creating an issue or PR."
  - name: "💬 Questions & Help"
    url: https://github.com/aditsuru-git/prism-terminal/discussions
    about: "Please ask and answer questions here. Do not use issues for questions."
