# .github/ISSUE_TEMPLATE/feature-request.yml

name: "🚀 Feature Request"
description: "Propose a new feature or a self-contained work chunk."
title: "[FEAT] <A short, descriptive title for the feature>"
labels: ["feature", "needs-scoping"]
body:
  - type: markdown
    attributes:
      value: "### Thanks for proposing a new feature! Please provide the following details to help us scope the work."

  - type: textarea
    id: problem-description
    attributes:
      label: "1. What is the goal of this feature?"
      description: "Describe the problem this feature solves or the value it adds. What is the user story?"
      placeholder: "As a [type of user], I want to [perform some action] so that I can [achieve some goal]."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: "2. What is the proposed solution?"
      description: "Describe the 'execution chunk'. How will this feature work from a user's perspective? Keep it high-level."
      placeholder: "We will add a new settings page with a toggle to enable/disable notifications."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "3. Acceptance Criteria"
      description: "How will we know this feature is complete? Please list the specific, testable conditions."
      placeholder: |
        - A developer can see the new settings page.
        - The notification toggle is present and functional.
        - Toggling it off stops emails from being sent.
    validations:
      required: true

  - type: input
    id: dependencies
    attributes:
      label: "4. Dependencies"
      description: "Are there any other issues or PRs that this work depends on? (Optional)"
      placeholder: "e.g., Issue #42, PR #55"
    validations:
      required: false
