name: Protect `main` Branch
on:
  pull_request:
    types: [opened, reopened]
    branches: ["main"]
permissions:
  pull-requests: write
jobs:
  comment-on-pr:
    name: Comment on PR to Main unless from Dev
    runs-on: ubuntu-latest
    if: github.head_ref != 'dev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Add Explanatory Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "🚨 **Pull Request Warning** 🚨

          > This Pull Request is targeting the \`main\` branch directly from a feature branch (\`${{ github.head_ref }}\`).
          >
          > Please consider **opening a PR** targeting the \`dev\` branch instead. Only the \`dev\` branch should typically be merged into \`main\`.
          >
          > Thank you!"
