name: Ruff Auto-Formatter
on:
  pull_request:
    branches:
      - "dev"
      - "test-**"

permissions:
  contents: write
  pull-requests: write

jobs:
  format-and-commit:
    name: Format Code with Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv and Ruff
        run: |
          pip install uv
          uv pip install ruff --system

      - name: Run Ruff Formatter
        run: uvx ruff format .

      - name: Check for formatting changes
        id: git-check
        run: |
          if ! git diff --quiet; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Changes
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          # Configure git with a bot user
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Count the number of formatted files and store it in an environment variable for the next step
          echo "FILES_FORMATTED=$(git status --porcelain | wc -l)" >> $GITHUB_ENV

          # Add all changes, commit them, and push to the PR's branch
          git add .
          git commit -m "style: ✨ auto-format with Ruff"
          git push

      - name: Comment on PR
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
          --body "Formatted **${{ env.FILES_FORMATTED }}** file(s) with Ruff! ✨"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
